apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: pgdata, namespace: hiqode }
spec:
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 10Gi } }
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: postgres, namespace: hiqode }
spec:
  replicas: 1
  selector: { matchLabels: { app: postgres } }
  template:
    metadata: { labels: { app: postgres } }
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - { name: POSTGRES_DB, valueFrom: { secretKeyRef: { name: app-secrets, key: pgdatabase } } }
            - { name: POSTGRES_USER, valueFrom: { secretKeyRef: { name: app-secrets, key: pguser } } }
            - { name: POSTGRES_PASSWORD, valueFrom: { secretKeyRef: { name: app-secrets, key: pgpassword } } }
          ports: [{ containerPort: 5432 }]
          volumeMounts:
            - { name: data, mountPath: /var/lib/postgresql/data }
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: pgdata }
---
apiVersion: v1
kind: Service
metadata: { name: postgres, namespace: hiqode }
spec:
  selector: { app: postgres }
  ports: [{ port: 5432, targetPort: 5432 }]
